name: Demo using repo environment in a composite action
description: use environment defined in the repository 
inputs:
  repo_environment_var
runs:
  using: "composite"
  steps:
    - name: test env variables
      shell: bash # we have to set shell explicitly in a composite action
      run: |
        echo ${{ inputs.repo_environment_var }}  
        echo done with action
