name: demo read js file
description: Demo showing how to run javascript
inputs:
  file_path:
    required: true  # if 'required' is 'false', set a default value using default: somevalue
    type: string
outputs:
  data:
    description: "data"
    value: ${{ steps.read_json.outputs.result }} 
runs:
  using: "composite"
  steps:
    - name: checkout file
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{inputs.file_path}}
      # cone mode false means will checkout only the file/files mentioned in the path
      # default is true which checks out repository root level files unnecessarily for our case
        sparse-checkout-cone-mode: false 
    - name: call the javascript action
      uses: actions/github-script@v7
      id: read_json
      with:
      # comment the following to get json output result
      # result-encoding: string
        script: |
          try {
            const exec = require('${{ github.workspace }}/${{inputs.file_path}}')
            exec('pwd')
            return "success"
          } catch(err) {
            core.error("Error json data")
            core.setFailed(err)
          }
