name: demo read yaml
description: Demo showing how to read a yaml file attached to root-caller-workflow repo using two methods
# 1. directly in shell using jq
# 2. in javascript using another action
# example caller workflow .github/workflows/read_json_file.yml
inputs:
  file_path:
    required: true  # if 'required' is 'false', set a default value using default: somevalue
    type: string
outputs:
  data:
    description: "json data"
    value: ${{ steps.read_file.outputs.result }} 
runs:
  using: "composite"
  steps:
    - name: checkout file
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{inputs.file_path}}
      # cone mode false means will checkout only the file/files mentioned in the path
      # default is true which checks out repository root level files unnecessarily for our case
        sparse-checkout-cone-mode: false 
    - name: see what files were checked out
      shell: bash
      run: |
        ls -al $GITHUB_WORKSPACE
        ls -al $GITHUB_WORKSPACE/.github
        ls -al $GITHUB_WORKSPACE/.github/test-files   
    - name: read json directly in shell
      shell: bash
      run: |
        myvar=$(yq '.level0.level1.level2.level3.level4.list[0]' ${{ github.workspace }}/${{inputs.file_path}})
        echo $myvar
    #   myvar=$(jq '.level0.level1.level2.level3' ${{ github.workspace }}/${{inputs.file_path}})
    - name: install js-yaml
      shell: bash
      run: npm install js-yaml
    - name: call the javascript action to read the file
      uses: actions/github-script@v7
      id: read_file
      with:
      # comment the followingto get json output result
      # result-encoding: string
        script: |
          try {
            const yml = require('js-yaml')
            const fs = require('fs')
            const data = yml.load(fs.readFileSync('${{ github.workspace }}/${{inputs.file_path}}'))
            // var data = JSON.parse(jsonString)
             console.log(data)
             console.log(data.level0.level1.level2.level3.level4.list)
            return data
          } catch(err) {
            core.error("Error json data")
            core.setFailed(err)
          }
