name: Demo using env variables in a composite action
description: use env variables at different levels in an action
runs:
  using: "composite"
  steps:
    - name: test env variables
      shell: bash
      env: # env context in a composite action can only be used inside a step
        stepvar: this_is_stepvar
      run: |
        echo $stepvar   
        echo ${{ env.stepvar }}
    - name: update env variables
      shell: bash
      run: |
        echo "stepvar=stepvar_new" >> $GITHUB_ENV
    - name: test updated env variables
      shell: bash
      run: |
        echo $stepvar
        echo ${{ env.stepvar }}   
        echo done with action
