name: Demo showing how to call a nested action and a script
description: call a bash script and an action 
inputs:
  nested_action_file:
    required: true  # if 'required' is 'false', set a default value using default: somevalue
    type: string
  script_file:
    required: true 
    type: string       
runs:
  using: "composite"
  steps:
    - name: run a script
      shell: bash
      # GITHUB_CONTEXT: ${{ toJson(github) }}
      # How to scripts
      # The first two commands are anonymous, they run the script in the current shell, changes in environment sustain (e.g changing directory or defining env vars),
      # and the script does not need to be executable in the first two commands.
      # The third command (chmod ...) is required to run the fourth command which runs the  script in a new shell and any environmental changes made inside the 
      # script are not propagated to the current shell.
      run: |
        . ${{github.action_path}}/../../scripts/hello.sh 
        source ${{github.action_path}}/../../scripts/hello.sh
        chmod +x ${{github.action_path}}/../../scripts/hello.sh
        ${{github.action_path}}/../../scripts/hello.sh


