name: Demo showing how to call a nested action and a script
description: call a bash script and an action 
inputs:
  nested_action_file:
    required: true  # if 'required' is 'false', set a default value using default: somevalue
    type: string
  script_file:
    required: true 
    type: string       
runs:
  using: "composite"
  steps:
    - name: set env vars
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        scriptPath: ${{github.action_path}}/../../scripts/${{inputs.script_file}}
      run: |
        scriptPath2=~/$scriptPath >> GITHUB_ENV
        echo scriptPath2
        echo ~/$scriptPath
        ls -al ~/$scriptPath
        ls -al $scriptPath
    - name: test call a script
      shell: bash # we have to set shell explicitly in a composite action 
      run: |
        chmod +x $scriptPath2   
        ./$scriptPath2
        echo ${{ env.scriptPath }}
        echo ${{inputs.script_file}}
        echo ${{inputs.nested_action_file}} 
        echo $GITHUB_WORKSPACE 
        echo $GITHUB_ACTION_PATH
        echo $GITHUB_ACTION_REPOSITORY
        echo ${{ github.action_path }}
        echo ${{ github.action_repository }}
      # echo -al ${{ github }} 
      #  echo done with action
# echo -al ${{ github.action_path }}
# echo -al $GITHUB_WORKSPACE 
# echo -al ${{ github.action_path/../../ }}
