name: demo call a script in the same repo as this action, with script path given relative to .github directory
description: Showing how to call  a script from an action that was called by a workflow that may or may not be in
# the same repo as this action
inputs:
  script_path:
    required: true 
    type: string       
runs:
  using: "composite"
  steps:
    - name: run a script
      shell: bash
      # How to use scripts.
      # The first two commands are anonymous, they run the script in the current shell, changes in environment sustain (e.g changing directory or defining env vars),
      # and the script does not need to be executable in the first two commands.
      # The third command (chmod ...) is required to run the fourth command which runs the  script in a new shell and any environmental changes made inside the 
      # script are not propagated to the current shell.
      run: |
        source ${{github.action_path}}/../../${{inputs.script_path}}
        chmod +x ${{github.action_path}}/../../${{inputs.script_path}}
        ${{github.action_path}}/../../${{inputs.script_path}}
        echo action done


