name: Demo showing how to read and write files attached to caller workflow repo
on:
  workflow_call:
    inputs:
      json_file_path:
        required: true 
        type: string
      yaml_file_path:
        required: true 
        type: string
env:
  jsondata: test
jobs:
  job1:
    name: read a json file
    runs-on: ubuntu-latest
    steps:
    - name: checkout file
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{inputs.json_file_path}}
          ${{inputs.yaml_file_path}}
      # cone mode false means will checkout only the file/files mentioned in the path
      # default is true which checks out repository root level files unnecessarily for our case
        sparse-checkout-cone-mode: false 
    - name: see what files were checked out
      run: |
        ls -al $GITHUB_WORKSPACE
        ls -al $GITHUB_WORKSPACE/.github
        ls -al $GITHUB_WORKSPACE/.github/test-files       
    - name: call the action to read a json file
      uses: actions/github-script@v7
      id: read_json
      with:
      # result-encoding: string
        script: |
          try {
            const fs = require('fs')
            const jsonString = fs.readFileSync('${{ github.workspace }}/${{inputs.json_file_path}}')
            var data = JSON.parse(jsonString)
            // console.log(data)
            // console.log(data.level0.level1.level2.level3.level4.list)
            return data
          } catch(err) {
            core.error("Error json data")
            core.setFailed(err)
          }
    - name: setup node 
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: install npm package  
      run: |
        npm install js-yaml
    - name: read data output from previous step
      run: |
        echo ${{steps.read_yaml.outputs.result}}
    - name: call the action to read a yaml file
      uses: actions/github-script@v7
      id: read_yaml
      with:
      # commenting the following will will set encoding to json
      # result-encoding: string
        script: |
          try {
            const yaml = require('js-yaml');
            const fs = require('fs')
            const data = yaml.load(fs.readFileSync('${{ github.workspace }}/${{inputs.yaml_file_path}}'))
            // console.log(data)
            // console.log(data.level0.level1.level2.level3.level4.list)
            return data
          } catch(err) {
            core.error("Error yaml data")
            core.setFailed(err)
          }
    - name: read data output from previous steps
      run: | 
        echo "${{env.jsondata}} = newtest" >>$GITHUB_ENV
        echo ${{env.jsondata}}
    - name: log output
      run: | 
       echo ${{env.jsondata}}
      # ${{steps.read_json.outputs.result}}">> $GITHUB_ENV
      #  echo '${{env.jsondata.level0.level1.level2.level3.level4.list}}'
      #  echo yamldata=${{steps.read_yaml.outputs.result}} >> GITHUB_ENV
      #  echo ${{yamldata.level0.level1.level2.level3.level4.list}}
        
