name: Demo showing how to reand and write files attached to caller workflow repo
on:
  workflow_call:
    inputs:
      file_path:
        required: true 
        type: string
jobs:
  job1:
    name: read a json file
    runs-on: ubuntu-latest
    steps:
    - name: checkout file
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{inputs.file_path}}
      # cone mode false means will checkout only the file/files mentioned in the path
      # default is true which checks out repository root level files unnecessarily for our case
        sparse-checkout-cone-mode: false 
    - name: see what files were checked out
      run: |
        ls -al $GITHUB_WORKSPACE
        ls -al $GITHUB_WORKSPACE/.github
        ls -al $GITHUB_WORKSPACE/.github/test-files       
    - name: call the action to read a json file
      uses: actions/github-script@v7
      id: read_json
      with:
        result-encoding: string
        script: |
          try {
            const fs = require('fs')
            const jsonString = fs.readFileSync('${{ github.workspace }}/${{inputs.file_path}}')
            var data = JSON.parse(jsonString)
            console.log(data)
            console.log(data.glossary.GlossDiv.GlossList.GlossEntry.GlossDef.GlossSeeAlso)
          } catch(err) {
            core.error("Error while reading or parsing the JSON")
            core.setFailed(err)
          }
