name: Demo showing how to reand and write files attached to caller workflow repo
on:
  workflow_call:
    inputs:
      file_path:
        required: true 
        type: string
jobs:
  job1:
    name: read a json file
    runs-on: ubuntu-latest
    steps:
    - name: checkout file
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{inputs.file_path}}
          sparse-checkout-cone-mode: false
    - name: call the action to read a json file
      uses: actions/github-script@v7
      id: read_json
      with:
        result-encoding: string
        script: |
          try {
            const fs = require('fs')
            const jsonString = fs.readFileSync('${{ github.workspace }}/${{inputs.file_path}}')
            var data = JSON.parse(jsonString)
            console.log(data)
            console.log(data.glossary.GlossDiv.GlossList.GlossEntry.GlossDef.GlossSeeAlo)
          } catch(err) {
            core.error("Error while reading or parsing the JSON")
            core.setFailed(err)
          }
