name: Demo using repo environment in a reusable workflow
on:
  workflow_call
jobs:
  job1:
    name: j1 test repo environment inside a job
    runs-on: ubuntu-latest
    environment: 
      prod
    steps:
      - name: test env variables
        run: |
          echo ${{ vars.ENV_PROD_VAR }}
          echo ${{vars.env_prod_var}}
          echo ${{ vars.ENV_PROD_VAR }}
          echo ${{ vars.ENV_DEV_VAR }}
          echo ${{ vars.ENV_STAGE_VAR }}
          echo done with reusable workflow       
