name: Demo showing how to call a bash script given in the .github directory of the called action
# We have to use an action that resides in the same repo as the called script for this task, thats the simplest way to do it
on:
  workflow_call:
    inputs:
      script_path:
        required: true 
        type: string
jobs:
  job1:
    name: j1 call an action from a reusable workflow
    runs-on: ubuntu-latest
    steps:
      - name: call the action 
        uses: workflows-and-actions/reusable-workflows-and-actions/.github/composite-actions/scripts_and_nested_calls@main
        with:
          script_path: ${{ inputs.script_path }} # relative to .github directory of the called reusable workflow/action
   
          
